### ISSUE TITLE
Error in shufflevector for DMD x86_64

### ISSUE THREAD

**Issue by DarkRiDDeR** [AuburnSounds/intel-intrinsics#36] opened 2019-09-08 16:51 UTC
Performing "release" build using /Library/D/dmd/bin/dmd for x86_64.
crypto 0.2.9+commit.3.gda3ac38: building configuration "library"...
../../intel-intrinsics-1.1.1/intel-intrinsics/source/inteli/types.d(271,30): Error: variable b used before set
../../intel-intrinsics-1.1.1/intel-intrinsics/source/inteli/types.d(269,30): Error: variable a used before set

This is a problem only for DMD x86_64. Release build for for DMD x86 occurs without errors.
Library with this problem https://github.com/shove70/crypto/pull/19

**Comment by baziotis** [comment] 2019-09-08 21:47
I can see the specific lines in the release 1.1.1 but I can't reproduce the error.
Neither does it seem to be an error.

Maybe this is a DUB problem.. I don't know, I'm not familiar with DUB.

Could you please provide a small snippet that uses the library and reproduces the error?

**Comment by DarkRiDDeR** [comment] 2019-09-09 15:29
```d
void main()
{
	__m128i t0;

	for (int i = 0; i < 1; i++)
	{
		auto t = _mm_unpacklo_epi64(t0, t0);
	}
}
```
``dub build -b release --arch=x86_64``

There will be such a mistake. And without a cycle it is not. It `s Magic?

**Comment by p0nce** [comment] 2019-09-09 20:07
Reproduced, and searching for a solution.

**Comment by p0nce** [comment] 2019-09-09 20:17
Fixed in v1.1.2 for this intrinsic, but probably more bugs still here when using shufflevector + DMD x86_64

**Comment by DarkRiDDeR** [comment] 2019-09-10 08:12
For ``_mm_unpackhi_epi64`` the same problem

**Comment by p0nce** [comment] 2019-09-10 12:59
shufflevector is slow to build anyway and LDC can generate the right instruction without it, so it's a chance to use it less (for fixed pattern)

**Comment by DarkRiDDeR** [comment] 2019-09-12 04:14
Everything is fine with LDC. But there is also a reference DMD. Therefore, everything should work with him too.
P.S. Oh, this DMD, he does a lot of something somehow wrong

**Comment by DarkRiDDeR** [comment] 2019-09-14 16:36
By the way, in similar functions the same bug should be

**Comment by p0nce** [comment] 2019-09-15 11:29
Yes, I just lack the time to fix it right now :) but will do eventually.

**Comment by p0nce** [comment] 2019-09-15 11:29
Thanks for your fix BTW

**Comment by DarkRiDDeR** [comment] 2019-09-15 12:45
Don’t mention it 😊

**Comment by p0nce** [comment] 2020-02-11 13:24
Superseded by #43

**Closed by p0nce** 2020-02-11 13:24 UTC
Labels: bug
